name: Basic Tests
on: push
jobs:
  build:
    name: Build Basic Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -Dbenchmark=on
          make   